services:
    crypto-trading:
        build: .
        container_name: crypto-trading-system
        ports:
            - "8080:8080"
            - "8501:8501"
        env_file:
            - .env
        volumes:
            - ./data:/app/data
            - ./logs:/app/logs
            - ./config:/app/config
        environment:
            - UPBIT_ACCESS_KEY
            - UPBIT_SECRET_KEY
            - TZ=Asia/Seoul
              # restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 512M
                    cpus: "0.5"
                reservations:
                    memory: 256M
                    cpus: "0.25"
        networks:
            - crypto-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/_stcore/health"]
            # test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

networks:
    crypto-network:
        driver: bridge

volumes:
    crypto-data:
        driver: local
    crypto-logs:
        driver: local
